spring.main.banner-mode=log
logging.level.org.springframework.boot.SpringApplication=INFO

chronicle-spring-logger.enabled=true
chronicle-spring-logger.queuePath=data/log-queue
chronicle-spring-logger.rollCycle=DAILY
chronicle-spring-logger.pollIntervalMs=5
chronicle-spring-logger.consumerThreadName=chronicle-log-consumer
chronicle-spring-logger.logFilePath=logs/app.log
chronicle-spring-logger.maxHistoryDays=30
chronicle-spring-logger.totalSizeCap=1GB
chronicle-spring-logger.logPattern=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %X{PID} --- [%20X{THREAD_NAME}] %X{LOGGER_NAME} : %msg%n
